name: Hola mundo Actions GH

on:
    push:
        branches:
            - main

jobs:
    hola_mundo:
        name: Imprimir Hola mundo
        runs-on: ubuntu-latest
        steps:
            - name: Revisar el repo
              uses: actions/checkout@v2

            - name: Install pandas
              run: pip install pandas

            - name: Ejecutar codigo de pthon
              run: python3 app.py 